### ISSUE TITLE
Tests give System.TypeInitializationException exception.

### ISSUE THREAD

**Issue by aytekgul** [reyntjesr/Hdf5DotnetTools#15]
I have downloaded, extracted and run the tests.
All 28 test fail with below message:

Assert.Fail failed. Unexpected exception of type System.TypeInitializationException caught: The type initializer for 'HDF.PInvoke.H5F' threw an exception.
![image](https://user-images.githubusercontent.com/100721041/156888809-e10f425b-68a5-4e94-84bd-1614e6495e4b.png)

My computer properties:
![image](https://user-images.githubusercontent.com/100721041/156888855-9cf86870-d7cf-4d4d-8472-d29a6048ee3e.png)

My Visal Studio properties:
![image](https://user-images.githubusercontent.com/100721041/156888920-7f0881ab-a886-4c7a-af71-380c3a693838.png)

**Comment by reyntjesr** [comment]
I think the nuget package hdf.pinvoke was missing in the unit tests. 
If you pull to the latest version all unit tests should work except one. I'm still working on that failing test.

**Comment by atekgul** [comment]
> I think the nuget package hdf.pinvoke was missing in the unit tests. If you pull to the latest version all unit tests should work except one. I'm still working on that failing test.

Thanks reyntjesr. I did the same thing before, but now it worked as you said.
![image](https://user-images.githubusercontent.com/12585814/157251517-62834624-3baf-4816-b849-4812104919b0.png)
