### ISSUE TITLE
Edit AppendDataset() function in ChunkedDataset.cs 

### ISSUE THREAD

**Issue by SBahre** [reyntjesr/Hdf5DotnetTools#4]
The last two lines of [AppendDataset()](https://github.com/reyntjesr/Hdf5DotnetTools/blob/master/Hdf5DotNetTools/ChunkedDataset.cs#L78) code are

```
H5D.close(memId);
H5D.close(filespaceId);
```
Because of this, code gives a runtime errror 
**H5Dclose(): not a dataset
    major: Invalid arguments to routine
    minor: Inappropriate type** 

_memId_ and _filespaceId_ are not the Datasets. They are the Dataspaces. H5D must be changed to H5S.
```
H5S.close(memId);
H5S.close(filespaceId);
```

**Comment by reyntjesr** [comment]
Sorry for the late reaction I was quite busy with other projects.
This was already corrected in the Develop_1_10 branch of this project. 
I have merged the master branch with the current develop_1_10 branch

**Comment by SBahre** [comment]
Hi,

I would like to contribute to your Hdf5DotnetTools library like

Regards,
Shubham Bahre
http://www.e-astitva.in
http://www.kavyafoundation.in
