### ISSUE TITLE
Similar Issue to #4 in ReadDatasetToArray() function in Hdf5Dataset.cs

### ISSUE THREAD

**Issue by SBahre** [reyntjesr/Hdf5DotnetTools#5]
Following line [in the code](https://github.com/reyntjesr/Hdf5DotnetTools/blob/master/Hdf5DotNetTools/Hdf5Dataset.cs#L61) is giving a Runtime Error: **H5D() close not a dataset**
`H5D.close(typeId)`

No need to close the [typeId variable](https://github.com/reyntjesr/Hdf5DotnetTools/blob/master/Hdf5DotNetTools/Hdf5Dataset.cs#L61) because it is not a dataset. 
You can verify it from the [variable declaration](https://github.com/reyntjesr/Hdf5DotnetTools/blob/master/Hdf5DotNetTools/Hdf5Dataset.cs#L46).

Solution: Remove the line of code.

**Comment by reyntjesr** [comment]
Again sorry for the late reaction
Thanks for spotting this. I have corrected the code.
