### ISSUE TITLE
WriteCompounds generating an error H5Tinsert

### ISSUE THREAD

**Issue by SBahre** [reyntjesr/Hdf5DotnetTools#6]
Using [WriteCompounds](https://github.com/reyntjesr/Hdf5DotnetTools/blob/master/Hdf5Tests/Hdf5CompoundTests.cs#L63) gives the following error in the console window

_**HDF5-DIAG: Error detected in HDF5 (1.10.0-patch1) thread 4520:
  #000: D:\build\HDF5\1.10.0-patch1\hdf5-1.10.0-patch1\src\H5Tcompound.c line 347 in H5Tinsert(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type**_

Although it does not hamper the writing process and you can still view the HDF5 in HdfView.

The error originates [from](https://github.com/reyntjesr/Hdf5DotnetTools/blob/master/Hdf5DotNetTools/Hdf5Compounds.cs#L96)
H5T.insert(typeId, cmp.name, Marshal.OffsetOf(t, cmp.name), **cmp.datatype**);

Found a solution to suppress this error.

`typeLong = GetDatatype(cmp.type);
                H5T.insert(typeId, cmp.name, Marshal.OffsetOf(t, cmp.name), typeLong); `

**Comment by reyntjesr** [comment]
I don't get this error when I do the unit tests. But I changed it anyway like you suggested.
Thanks again! And if you have any other suggestions let me know.

**Comment by SBahre** [comment]
Hey, I discovered something related to this error. I raised this issue  because I was getting this message
![image](https://user-images.githubusercontent.com/33088399/34482511-70aa8d4a-efde-11e7-9842-436d5bdd9b54.png)
Twice because I read two compound datasets.

Code A: 
`H5T.insert(typeId, cmp.name, Marshal.OffsetOf(t, cmp.name), cmp.datatype);`
This was your original code which is generating the above error message on the console window. This message does not affect the reading and writing the compound dataset, i.e., you can still read and write the compound dataset perfectly well.

Code B:
```
var typeLong = GetDatatype(cmp.type);
H5T.insert(typeId, cmp.name, Marshal.OffsetOf(t, cmp.name), typeLong);
```
Code B was my suggestion.

I had asked you to change from code A to code B which you already did and code B successfully suppressed the error message. You can still read and write the compound dataset perfectly well.

Now I came across something interesting. 
If I use code A, 
I can read the data perfectly using `ReadCompounds()` function as well as see it in the HDFviewer.

If I use Code B, 
I can read the data using `ReadCompounds()` function and **can not see it in the HDFviewer**.

I would further like to contribute to this code. I would be sending you more reviews and findings of this code if you like.
