### ISSUE TITLE
Handling array in Struct

### ISSUE THREAD

**Issue by MMike0782** [reyntjesr/Hdf5DotnetTools#9]
I'm trying to create an array in a struct;

[StructLayout(LayoutKind.Sequential)]
    public struct Responses
    {
        public Int64 MCID;
        public int PanelIdx;
        //this is not handled in struct, get error trying to handle array as simpleType in HDF5Common.GetDatatype
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 20)]
        public  short[] ResponseValues;
}

Is this possible with the current version?

Regards

Mike

**Comment by reyntjesr** [comment]
It should be possible and I gave it a try this weekend but it's been a while since I've made big changes to this library, so I'm a bit rusty. 
I hope I find some more time this week and I'll let you know when I've found a solution

**Comment by JonaWer** [comment]
I had the same problem and managed it by changing the GetCompoundInfo-Method within the foreach-loop:

var fldType = x.FieldType;
var marshallAsAttribute = type.GetMember(x.Name).Select(m => m.GetCustomAttribute<MarshalAsAttribute>()).FirstOrDefault();

OffsetInfo oi = new OffsetInfo()
{
    name = x.Name,
    type = fldType,
    datatype = !fldType.IsArray ? ieee ? GetDatatypeIEEE(fldType) : GetDatatype(fldType)
	: H5T.array_create(ieee ? GetDatatypeIEEE(fldType.GetElementType()) : GetDatatype(fldType.GetElementType()), (uint)fldType.GetArrayRank(), Enumerable.Range(0, fldType.GetArrayRank()).Select(i => (ulong)marshallAsAttribute.SizeConst).ToArray()),
    size = fldType == typeof(string) ? StringLength(x) : !fldType.IsArray ? Marshal.SizeOf(fldType) : Marshal.SizeOf(fldType.GetElementType()) * marshallAsAttribute.SizeConst,
    offset = 0 + curSize
};

Regards
Jona

**Comment by reyntjesr** [comment]
Great, it works! Thanks!
I added an extra unit test that writes an array that contains a struct with an array
